LICENSE
This adds the necessary license file for this repository.
=> Add CC-BY-4.0 LICENSE file

README.md, build_pdfs_with_docker.sh, docker/Dockerfile, docker/entrypoint.sh
This makes it easy to make sure that the book is built in a reproducible
way on different machines.
=> Add docker container to build the book.

book.md
The introduction explains:
1. The purpose of the book.
2. The intended audience.
3. Why we started creating this book:
- We don't know of any other similar ones.
- There is a need for a book like this.
4. Explain why we chose to develop this book as an open source project.
5. Give some basic pointers on how readers can contribute to the book.
=> Write an initial introduction

book.md
=> Renamed 'side channel' to 'side-channel' with hyphen to better conform to external terminology.

book.md
Discussed as part of issue #62. This PR updates the book heading to better reflect the content of the section, and aligns it with README.md.
=> Update heading to better reflect content

book.md
Side channels and covert channels are the basis for the attacks that make use
of them, which are described in later chapters.  Let's see if it makes sense to
separate out the description of covert channels from the actual attacks making
use of them. (I currently think it does make sense, but we probably will only
know when the chapters are far more complete).
If it turns out later that it's best to structure this content differently, we
can of course restructure it. For now, I think the restructuring in this commit
helps to unblock progress on writing content that should be in the book.
This commit only contains the introduction and a few needed section titles of
the covert channel and side-channel chapter. In the spirit of incremental
development, I think this is a useful increment to …
=> Side-channel and covert channel chapter introduction

book.md
=> Replace "stack overflow" with "stack buffer overflow"

book.bib, book.md
An introduction to read/write primitives and how they can be used. PTAL!
=> Add section on exploitation primitives

book.md
This is incrementally adding content to be able to explain cache covert channels
=> Add CPU cache architecture section

book.bib, book.md
and also shorten chapter two title (#94)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/124)
=> Add section on sanitizers

book.md, theme/html/pandoc_template.html
This adds 2 buttons in the top row:
* One button to go to the llsoftsecbook github repository.
* One button to open the github page that enables to edit the book text and immediately create a commit/pull request in the browser.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/137)
=> [HTML] Add github repo and edit buttons.

theme/html/pandoc_template.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/138)
=> Minor fixups

.gitattributes, build_with_docker.bat
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/142)
=> add build_with_docker.bat to make building on Windows easy.

theme/html/pandoc_template.html
I hope this will make it easier for readers to report issues they see in the content of the book. I hope it will also make it more likely for readers to report the issues they see.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/146)
=> [HTML] Add a "report issue" button.

book.bib, book.md
... by referring to the work of Wu2018 and Soares2021.
This aims to fix #149.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/151)
=> Improve timing side-channel discussion

Makefile, book.md, theme/html/markup_issue.lua, theme/html/markup_todo.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/160)
=> Enable easily creating links to GitHub issues

book.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/184)
=> Add links to github issues for todos.

book.md
Fixes typos in #188
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/189)
=> #188 Fixed typos.

book.md
We aim to use US spelling consistently in the book...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/190)
=> Use US spelling (popularized)

book.md, theme/html/pandoc_template.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/185)
=> [HTML] Add Discord button

book.bib, book.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/193)
=> Add section on JIT vulnerabilities (#171)

README.md
We have created a Discord server recently.
In the README section that explains how to share feedback, also list the Discord server as one of the options.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/194)
=> Mention Discord in README.md

book.bib, book.md
I expect that after introducing this text, it becomes possible to then go on an start writing about transient attacks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/204)
=> Write about cache-predictor-based side channels

book.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/208)
=> Issue 183 is fixed, remove todo.

book.bib
The titles aren't displayed at all before this fix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/210)
=> Escape special characters in citations

book.bib, book.md
...also fix missing punctuation in an earlier section
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/209)
=> Add section on bounds checking

book.md
There is no intent to change the meaning of any of the text.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/221)
=> Improve wording in branch predictor side channel section

book.md
There is no intent to change the meaning of the text; just trying to make the text a bit easier to read.
I've also made definitions of terms stand out consistently by making them bold.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/220)
=> Improve wording in cache side channel section

book.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/226)
=> Fix TODO formatting

Makefile, theme/html/add_edit_to_headers.lua, theme/html/default.css
The intent is that this makes it easier for a reader to make a suggestion for improvement when they read the book: they simple click one of the "pencil" icons next to each header. The will bring them to the interactive github interface to edit the source of the book near that header.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/227)
=> Add an edit button after every header.

book.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/231)
=> Correct copyright years

Makefile
This PR is the first successful attempt to generate an EPUB book. Next steps would be to customize the cover, improve the quality of the images, styling with CSS, etc. Addresses https://github.com/llsoftsec/llsoftsecbook/issues/211
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/233)
=> Outputting epub format

Makefile, theme/html/pandoc_template.html
This adds a download button to the HTML version of the book, which enables downloading the html, pdf and epub version of the book.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/235)
=> [HTML] Add download button

.github/workflows/main.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/236)
=> [precommit testing] add epub to uploaded artifacts

Makefile, theme/epub/epub_llsoftsecbook.css
The styling of TODOs can for sure be improved further. Hopefully, creating an initial CSS helps with incrementally improving the look of the epub format.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/238)
=> [EPUB] create initial CSS, styling TODOs

book.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/244)
=> Explain what TODO items are about in the introduction.

book.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/247)
=> Remove list of todos from PDF output to workaround #246

book.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/250)
=> Expand abbreviation BTB: Branch Target Buffer

book.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/252)
=> Fix a link

book.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/253)
=> Fix another link

theme/html/pandoc_template.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/257)
=> Add button to enable sharing to bluesky

book.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/260)
=> Add todo to cover more of pauthabi

book.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/262)
=> Add todo and missing index to COOP section
