- .github/workflows/main.yml
This builds the book's PDF using the docker image and stores the
produced PDF as a github action artefact, so it becomes easy to download
from the github UI when the CI job has run.
This depends on #13
> Add basic ci

- Makefile
- book.md
- docker/Dockerfile
This is based on latex makeindex functionality.
Adding a word to the index in the markdown text is as simply as
writing \index{word-to-add-to-index}.
> Add ability to add items to index.

- book.md
- docker/Dockerfile
The idea is that this makes it possible to develop content for the book using a similar trick as with software development where one sometimes writes "FIXME" or "TODO" comments to not get mentally stuck on a detail.
The hope is that having a simple way to jot down TODOs while writing content helps to make a note that more detail could be added to a section; while not holding up getting a section into review before that detail is added.
> Introduce the ability to add todos inline in the document

- .github/workflows/main.yml
- Makefile
This is done by running a github action step publishing the entire build
directory to the gh-pages branch. This only done for build actions that
are run on the main branch, and only when triggered by a push (and not
e.g. by a pull request).
One other minor addition is to make the book.html also available under
index.html, so that that's the page that gets picked up automatically on
the github pages webpage.
> Automatically publish to github pages

- Makefile
- pandoc_template.html
- pandoc_template.tex
The 2 commits in this pull request result in both copyright and license information to be present in both the PDF and the HTML version of the book.
The copyright info is extracted directly from the metadata in the YAML block at the start of the book.md file. That way, the copyright info comes directly from the copyright info in source form in book.md. Hopefully that will make it easier to keep copyright info consistent and correct.
To be able to extract that info from the YAML header, I believe the most straightforward way is to customize the template pandoc uses to produce PDF/HTML output.
Using a custom template may well be beneficial in the future too when we want to improve e.g. the layout/design of the HTML output.
The license info is hard-coded into the template files/not derived …
> Add copyright and license info

- .gitignore
Developers using Visual Studio Code will have a .vscode directory in the clone
of the repository. Let git ignore it.
> Git ignore .vscode directory

- .github/workflows/main.yml
- Makefile
- docker/Dockerfile
- pandoc_template.html
- pandoc_template.tex
This automatically computes a version number from the book, using the "git
describe" command.
"git describe --match '0'" looks for the tag with name "0", and computes a
string following the following pattern:
"tag"-"nr of commits since that tag"-g"current commit hash".
By having a tag with name "0" pointing to the first commit of the project's
history, this produces a version string looking like
0-"nr of commits since initial commit"-g"current commit hash".
For example: 0-56-gcebad2f.
Using this as a version string has the following advantages:
- The version name starts with "0" suggesting the book isn't complete yet.
- Since we maintain a linear history in this project, the second number
will be a nice linearly increasing number, allowing humans to quickly
which of two versions is more …
> Automatically compute a version number.

- default.css
This commit addresses issue #32 by adding some basic 'responsive design' CSS to the default.css file such that the page layout is minimally adjusted when the viewport is less than 720px in width.
The effects of this change can be seen at:
https://jlouiskaplan-arm.github.io/llsoftsecbook/ 
(Note the changes only take effect with a viewport width of less than 720px.)
The main changes made for small screens are moving the contents above the paragraph elements and justifying paragraph text.
The advantage of the 'responsive design' approach is that changes made for small screens have no effect on the large screen styling.
> Make small/mobile screen view more readable

- book.md
The word discussion was present a few times in this and surrounding sentences. Remove one occurrence and replace it with analyzing, which hopefully results in a slightly more pleasant reading experience.
> Slight improvement in wording: discussing -> analyzing

- build_with_docker.sh
- docker/Dockerfile
* Ensures that build output using
the docker build script belongs
to the user who triggered the build.
* Achieves this by adding a docker user
with same uid and uname as the user who
starts the docker build process and activates
this user by default for the entrypoint.
> Make build output belong to user who starts build

- Makefile
- docker/Dockerfile
This makes it possible to refer to figures from text.
See https://github.com/tomduck/pandoc-fignos for details.
This will be used by upcoming book content.
> Add suppport for pandoc-fignos filter

- book.md
I accidentally used \href instead of the correct way to add
links, breaking the PDF and HTML output. The fix is obvious.
> Fix broken references

- book.md
The project name's preferred capitalisation is intended to emphasise the 'TTY' at the end.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/122)
> Copy-edit: correct spelling of PuTTY.

- theme/html/default.css
- theme/html/pandoc_template.html
This is a first step towards moving to a much better HTML version of the book, see discussion in issue #32.
In this commit, the bare minimum has been done to recreate the existing layout with bootstrap. I've tried to add sufficient comments in the pandoc_template.html file so that it should be clear what each line does. I hope that will help with keeping the template file maintainable.
I see this is a first step on a longer road towards making a much nicer-looking HTML output, aiming for something similar to what Rust's mdbooks or bookdown.org books look like.
Note that by moving to bootstrap, the font seems to change a bit, and there is more spacing between lines. Not sure if we should consider trying to move back to the denser text from what we had before, or if we should stick with …
> Use bootstrap for HTML output

- theme/html/default.css
- theme/html/pandoc_template.html
For now, one button is introduced: TOC.
When clicked, it opens up a modal with the table of contents.
After experimenting with a number of different options on how to display the table of contents, it seemed best to me to just always leave it behind a button and a modal, so that independent of screen size it works the same.
I hope that labeling the button with "TOC" is intuitive enough for people to see that they have to click there to find the table of contents.
We could change this later for really large screens to still show a table-of-contents in a left-or-right hand column. I'm not sure at the moment if that will be best even for large-screen sizes at the moment, as I'd also like to have margin notes to display things such as footnotes, todos and maybe references/citations.
Let's …
> [HTML] Introduce title row with TOC button

- theme/html/pandoc_template.html
The main content pane has class col-lg-8 by default.  When the TOC sidebar is visible, which has col-lg-4, this nicely divides the screen between the 2 columns.
However, when the TOC is made invisible, that leaves screen space unused (only 8 of the 12 bootstrap columsn are used), resulting in a scrollbar not appearing at the right hand side, but maybe at 2/3ths of the screen.
Fix this by adding/removing the col-lg-8 class from the main content based on TOC visibility/invisibility.
This commit also fixes a second thing on small screens.  Before, when the TOC was made visible, the main content pane also remained visible, albeit below the TOC. This could lead to confusing views with 3 scrollbars, and just not looking good. Therefore, for small screens always show either the TOC or the main …
> [HTML] Fix scrollbar position on large screens

- Makefile
- theme/html/convert_to_sidenote.lua
- theme/html/default.css
- theme/html/pandoc_template.html
This change adds a sidenotes margin on the right hand side. It puts the footnotes in the right hand margin rather than at the bottom of the document.
To make space for the sidenote marging, the TOC on the left hand side only gets shown by default on xl screens.
To implement this required doing more things outside of the bootstrap framework. As a result, we don't use the bootstrap framework for sizing "columns" anymore. We still do use other features of the bootstrap framework.
On smaller screens, the "sidenotes" get displayed inline, i.e. there is a responsive design for this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/139)
> [HTML] Add sidenotes, converted from footnotes

- theme/html/convert_to_sidenote.lua
- theme/html/default.css
This shows todo's and missing contents as side notes in the HTML output.
For small screens, where sidenotes are shown inline, this commit does not show the todos or missingcontents at all. It could be chosen later to have an indication (small button?) that the reader could click to make todos/missingcontent info visible.
We could also implement a button in the top row to toggle visibility of todos/missingcontent.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/140)
> [HTML] Show \todo and \missingcontent as sidenote.

- theme/html/pandoc_template.html
... rather than to the left, so that a tooltip is less likely to hide other buttons.
However, for this first button ("toggle TOC"), this does not seem to be working: the tooltip continues to be shown on the right hand side, i.e. over the other buttons.
I could not find a way to change the behaviour.
Overall, this still is an improvement for the other buttons.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/141)
> [HTML] Make tooltips appear on the bottom of buttons

- theme/html/default.css
... By computing available width based on 100% rather than on 100vw. For more background on the issues with using the vw unit on Windows, see
https://stackoverflow.com/questions/23367345/100vw-causing-horizontal-overflow-but-only-if-more-than-one
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/143)
> Fix pane size issues on Windows

- theme/html/pandoc_template.html
On touch screen devices, the tooltips are not really useful. They only pop up after the user already pushes the button, so they are then already "activating" the button action.
Therefore, disable them on touch devices.
The most consistent advice when looking for how to do that seems to be to use "ontouchstart" in document.DocumentElement. At least in Firefox this seems to work as expect across desktop and mobile.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/144)
> [HTML] Do not show tooltips on touch screen devices.

- theme/html/pandoc_template.html
... to be able to easily share a pointer to the HTML version of the book on social media.
This uses https://developer.mozilla.org/en-US/docs/Web/API/Web_Share_API api where available.
This web share api is mostly not implemented on desktop browsers.
On mobile browsers where it is implemented, this (I hope) pops up a native "share" functionality, that lets the user choose between whichever app they have installed to share.
When the web share api is not available, it uses a fall-back technique with a drop-down menu that shows a number of the most popular social media. For now, that drop-down menu shows 3 options: twitter, mastodon and linkedin. We could add more if we think that would be useful.
On Safari on desktop, this web share api is implemented, but does not by default allow to share …
> [HTML] Add a "share" button

- theme/html/default.css
Section symbol was always present for h4 elements, which is inconsistent with behaviour for other h* elements.
This patch makes h4 behaviour consistent with h1-3 by making the section symbol appear only when mouse is hovered over an h4 element.
Fixes #147
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/148)
> [HTML] only show section symbol for h4 on hover

- book.bib
- book.md
This is the draft I was discussing with @kbeyls in #183.
One thing that I was thinking about is if this should be a separate chapter or it should be somehow integrated with the chapter about supply chain attacks. Any ideas?
This is far from perfect so any feedback is welcomed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/200)
> Add chapter about compiler introduced security vulns

- book.md
Aim to use general names rather than names for specific implementations. Based on feedback from
https://twitter.com/matt_dz/status/1672375841844518915
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/207)
> Improve names for branch predictor components

- theme/html/default.css
This might be a cosmetic choice, but (horizontally) centered figures seem to flow better.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/217)
> Centre figures.

- book.md
Again, not intend to change any of the meaning of the text; just trying to make it slightly easier to read and process.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/222)
> Improve wording in transient execution section

- Makefile
- book.md
- docker/Dockerfile
- docker/entrypoint.sh
- theme/fignos.lua
- theme/html/clickable_headers.lua
- theme/html/default.css
- theme/tex/pandoc_template.tex
pandoc-fignos is no longer supported on recent pandoc versions, so instead, this commit adds the simple lua script theme/fignos.lua that implements just the functionality that we are using. This results in the figure numbering in the PDF to no use chapter-based numbering (e.g. figure 2.3 for the 3rd figure in chapter 2), but rather uses linear numbering (figures are numbered from 1 to N throughout the whole document). This makes it consistent with how they are numbered in the HTML output, so could be argued to actually be an improvement.
Diffing the tex output before and after this patch shows that the only other difference is a minute difference in the links used for citations, which is presumably caused by using the pandoc built-in 'citeproc' rather than the deprecated pandoc-citeproc …
> Update pandoc to recent version (3.0.1) so that we can use grid tables.

- book.bib
- book.md
This patch only introduces a high-level categorization of transient execution attacks. The detailed description of the various Spectre-, Meltdown-, LVI-style attacks will be for later patches.
Note that the table uses the pandoc grid table syntax, see https://pandoc.org/chunkedhtml-demo/8.9-tables.html, section 8.9.4. The version of pandoc we use in our docker image does not support that yet. But it's the only variant of table that supports multi-row and multi-column cells which I'd like to use for this table. I'll need to figure out how to update the version of pandoc in the docker container we use. That in itself shouldn't be too hard. The annoying thing is that the pandoc filter pandoc-fignos that we use is no longer maintained and does not work anymore with recent versions of …
> Introduce transient execution attacks

- book.bib
- book.md
Removes extra []s around the @Cook2023 bib reference so the URL will render correctly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/228)
> book.md: fix bib reference typo for array bounds post

- .github/workflows/main.yml
The versions v2 that we used until now have been deprecated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/237)
> [precommit testing] update checkout and upload-artifact actions to v4

- book.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/245)
> Add paragraph on ROP gadgets and variable length instructions

- book.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/248)
> Fix an invalid link

- book.bib
The previous DOI was broken, so I updated the citation data. (This also adds keywords.)
I checked with a quick shell script that other DOIs don’t return 404s, so this should be the only error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/254)
> Update bibliography for Dullien2020

- theme/tex/pandoc_template.tex
Our docker file is based on Debian Trixie.
It seems that the pandoc version in debian trixie got updated, resulting
in breaking out pdf/latex build, because pandoc creates different latex
code for citations now.
Fixing that in this buid by updating our custom latex template to what
the pandoc default latex template uses for citeproc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/256)
> Update latex template after update of pandoc in Debian Trixie

- theme/fignos.lua
- theme/html/default.css
- theme/tex/pandoc_template.tex
This patch makes it possible to have example divs and definitions divs.
It also contains the necessarily functionality to reference these example and definitions from text.
As part of this same patch, since the functionality is similar, it also enables referring to specific sections.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/263)
> Add support for Example and Definitions; enable references them and section headers

- theme/html/pandoc_template.html
When writing new content, I often reload the HTML version of the book, to see what the result of new writing looks like once rendered.
It is very annoying that on reload, the page jumps back to the very top of the content.
This patch addresses that: on reload, the current scroll position is retained.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/266)
> Retain scroll position on page reload

- book.md
The introduction text explained a coarse-grained CFI scheme as having "relatively coarse granularity", which is a non-explanation – if someone is confused about what the "grain" metaphor means, it doesn't help them to just repeat the same word again. Expanded it to spell out that the "grains" in question are the equivalence classes of functions that the same branch is legally allowed to target.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/llsoftsec/llsoftsecbook/269)
> Clarify coarse- vs fine-grained CFI.
